import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DEFAULT_WORKFLOW,
  EventStore,
  KnowledgeStore,
  MemoryStorage,
  WorkflowEngine,
  WorkflowStateStore,
  transitionWorkflowStateV3,
} from '../dist/index.js';

const logger = { info() {}, warn() {}, error() {}, debug() {} };
const config = {
  rootPath: '.',
  specsDir: 'specs',
  knowledgeDir: 'sovei-flow/project/knowledge',
  harnessDir: 'sovei-flow',
  project: { name: 'test', description: 'test', techStack: {}, started: '2026-01-01' },
  workflow: { version: '2.0.0', stageOrder: DEFAULT_WORKFLOW.stageOrder },
};

function createEngine() {
  const storage = new MemoryStorage();
  return { storage, engine: new WorkflowEngine(storage, new KnowledgeStore(storage), logger, config) };
}

/**
 * Fast-forward through explore stage (sole entry) so tests can operate on grill+.
 * Writes exploration.md so grill's requiredArtifacts is satisfied.
 */
async function skipExplore(storage, featureId) {
  const path = `specs/${featureId}`;
  const store = new WorkflowStateStore(storage, `${path}/workflow-state.json`, DEFAULT_WORKFLOW.stageOrder);
  const current = await store.read();
  const prepared = transitionWorkflowStateV3(current, { type: 'prepare', actor: 'test' }, DEFAULT_WORKFLOW.stageOrder);
  await store.update(current.revision, () => prepared);
  await storage.write(`${path}/exploration.md`, '# 需求探索\n\n核心目标与代码现状。');
  const completed = transitionWorkflowStateV3(prepared, { type: 'complete', actor: 'test' }, DEFAULT_WORKFLOW.stageOrder);
  await store.update(prepared.revision, () => completed);
}

test('bootstrap is idempotent and preparation cannot complete placeholder artifacts', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('001-safe-state');
  await skipExplore(storage, '001-safe-state');
  const before = await storage.read('specs/001-safe-state/workflow-events.jsonl');

  const bootstrappedAgain = await engine.bootstrap('001-safe-state');
  assert.deepEqual(bootstrappedAgain.completedStages, ['explore']);
  assert.equal(await storage.read('specs/001-safe-state/workflow-events.jsonl'), before);

  const prepared = await engine.prepareStage('001-safe-state', 'grill');
  const template = await storage.read('specs/001-safe-state/decision-log.md');
  assert.match(template, /^# 决策日志/m);
  assert.match(template, /## 提示契约/);
  assert.match(template, /## 权威规则/);
  assert.match(prepared.prompt, /# 阶段：grill/);
  assert.doesNotMatch(template, /Generated by|Prompt Contract|Authority Rules/);
  await assert.rejects(
    engine.completeStage('001-safe-state', 'grill'),
    /still templates: decision-log\.md/,
  );
  await storage.write('specs/001-safe-state/decision-log.md', '# 决策\n\n已批准请求的行为。');
  const completed = await engine.completeStage('001-safe-state', 'grill');
  assert.deepEqual(completed.completedStages, ['explore', 'grill']);
});

test('implement blocks stage completion while tasks remain in JSON state', async () => {
  const { storage, engine } = createEngine();
  const path = 'specs/002-multi-task';
  await engine.bootstrap('002-multi-task');
  const stateStore = new WorkflowStateStore(storage, `${path}/workflow-state.json`, DEFAULT_WORKFLOW.stageOrder);
  let state = await stateStore.read();
  const implementIndex = DEFAULT_WORKFLOW.stageOrder.indexOf('implement');
  for (const stage of DEFAULT_WORKFLOW.stageOrder.slice(0, implementIndex)) {
    const prepared = transitionWorkflowStateV3(state, { type: 'prepare', actor: 'test' }, DEFAULT_WORKFLOW.stageOrder);
    await stateStore.update(state.revision, () => prepared);
    state = transitionWorkflowStateV3(prepared, { type: 'complete', actor: 'test' }, DEFAULT_WORKFLOW.stageOrder);
    await stateStore.update(prepared.revision, () => state);
  }
  const prepared = transitionWorkflowStateV3(state, { type: 'prepare', actor: 'test' }, DEFAULT_WORKFLOW.stageOrder);
  await stateStore.update(state.revision, () => prepared);
  await storage.write(`${path}/tasks.md`, '# Tasks\n\n- [ ] TASK-001: first\n- [ ] TASK-002: second\n');
  await storage.write(`${path}/change-manifest.md`, '# Changes\n\nTASK-001 implemented and verified.');

  await assert.rejects(engine.completeStage('002-multi-task', 'implement'), /unfinished tasks: TASK-001, TASK-002/);

  const currentJson = JSON.parse(await storage.read(`${path}/workflow-state.json`));
  currentJson.completedTaskIds = ['TASK-001', 'TASK-002'];
  await storage.write(`${path}/workflow-state.json`, JSON.stringify(currentJson, null, 2));
  await storage.write(`${path}/change-manifest.md`, '# Changes\n\nTASK-001 and TASK-002 implemented and verified.');
  state = await engine.completeStage('002-multi-task', 'implement');
  assert.equal(state.currentStage, 'converge');
});

test('event replay rejects a duplicate bootstrap event in a corrupted log', async () => {
  const storage = new MemoryStorage();
  const events = new EventStore(storage);
  const path = 'specs/003-corrupt';
  await events.append(path, { type: 'BOOTSTRAP', featureId: '003-corrupt' });
  await events.append(path, { type: 'BOOTSTRAP', featureId: '003-corrupt' });
  await assert.rejects(events.replay(path, DEFAULT_WORKFLOW), /Duplicate BOOTSTRAP/);
});

test('completeStage throws when stage was not prepared', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('004-no-prepare');
  await skipExplore(storage, '004-no-prepare');
  // grill stage exists, but prepareStage was never called
  await assert.rejects(
    engine.completeStage('004-no-prepare', 'grill'),
    /stage was not prepared/,
  );
});

test('prepareStage enables completeStage and records STAGE_PREPARED event', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('005-prepare-then-complete');
  await skipExplore(storage, '005-prepare-then-complete');
  const stateBefore = await engine.getState('005-prepare-then-complete');
  assert.deepEqual(stateBefore.preparedStages, []);

  await engine.prepareStage('005-prepare-then-complete', 'grill');
  const stateAfter = await engine.getState('005-prepare-then-complete');
  assert.deepEqual(stateAfter.preparedStages, ['grill']);

  await storage.write('specs/005-prepare-then-complete/decision-log.md', '# 决策\n\n已批准请求的行为。');
  const completed = await engine.completeStage('005-prepare-then-complete', 'grill');
  assert.deepEqual(completed.preparedStages, []);
  assert.deepEqual(completed.completedStages, ['explore', 'grill']);
});

test('new Feature bootstrap rejects a directory containing any pre-existing file', async () => {
  const { storage, engine } = createEngine();
  await storage.write('specs/006-legacy-input/old-state.yml', 'legacy: true');
  await assert.rejects(
    () => engine.bootstrap('006-legacy-input'),
    /must be empty|已有文件|pre-existing/i,
  );
  assert.equal(await storage.read('specs/006-legacy-input/old-state.yml'), 'legacy: true');
  assert.equal(await storage.read('specs/006-legacy-input/workflow-state.json'), null);
});

test('new Feature top-level operations use JSON state without EventStore fallback', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('007-json-only');
  assert.equal(await storage.read('specs/007-json-only/workflow-events.jsonl'), null);

  const initial = await engine.getState('007-json-only');
  assert.equal(initial.revision, 0);
  await engine.prepareStage('007-json-only', 'explore');
  const prepared = await engine.getState('007-json-only');
  assert.deepEqual(prepared.preparedStages, ['explore']);
  assert.equal(prepared.revision, 1);
  await engine.prepareStage('007-json-only', 'explore');
  const repeated = await engine.getState('007-json-only');
  assert.equal(repeated.revision, 1);
  const repeatedJson = JSON.parse(await storage.read('specs/007-json-only/workflow-state.json'));
  assert.equal(repeatedJson.history.length, 1);

  await storage.write('specs/007-json-only/exploration.md', '# 需求探索\n\n真实探索结果。');
  await storage.write('specs/007-json-only/sub-change-map.md', '# 拆分\n\nno-split');
  const completed = await engine.completeStage('007-json-only', 'explore');
  assert.deepEqual(completed.completedStages, ['explore']);
  assert.equal(completed.revision, 2);
  assert.equal(await storage.read('specs/007-json-only/workflow-events.jsonl'), null);
});

test('JSON-only status rejects missing or malformed state without replay', async () => {
  const { storage, engine } = createEngine();
  await storage.write('specs/008-invalid-json/workflow-events.jsonl', JSON.stringify({ type: 'BOOTSTRAP' }));
  await assert.rejects(() => engine.getState('008-invalid-json'), /Workflow state not found|not found/i);
  await storage.write('specs/008-invalid-json/workflow-state.json', '{broken');
  await assert.rejects(() => engine.getState('008-invalid-json'), /invalid JSON/i);
});
