import assert from 'node:assert/strict';
import test from 'node:test';
import {
  DEFAULT_WORKFLOW,
  EventStore,
  KnowledgeStore,
  MemoryStorage,
  WorkflowEngine,
} from '../dist/index.js';

const logger = { info() {}, warn() {}, error() {}, debug() {} };
const config = {
  rootPath: '.',
  specsDir: 'specs',
  knowledgeDir: 'sovei-flow/project/knowledge',
  harnessDir: 'sovei-flow',
  project: { name: 'test', description: 'test', techStack: {}, started: '2026-01-01' },
  workflow: { version: '2.0.0', stageOrder: DEFAULT_WORKFLOW.stageOrder },
};

function createEngine() {
  const storage = new MemoryStorage();
  return { storage, engine: new WorkflowEngine(storage, new KnowledgeStore(storage), logger, config) };
}

/**
 * Fast-forward through explore stage (sole entry) so tests can operate on grill+.
 * Writes exploration.md so grill's requiredArtifacts is satisfied.
 */
async function skipExplore(storage, featureId) {
  const events = new EventStore(storage);
  const path = `specs/${featureId}`;
  await events.append(path, { type: 'STAGE_PREPARED', stage: 'explore' }, 'explore');
  await storage.write(`${path}/exploration.md`, '# 需求探索\n\n核心目标与代码现状。');
  await events.append(path, { type: 'STAGE_COMPLETE', stage: 'explore', artifacts: ['exploration.md'] }, 'explore');
  await events.persistState(path, await events.replay(path, DEFAULT_WORKFLOW));
}

test('bootstrap is idempotent and preparation cannot complete placeholder artifacts', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('001-safe-state');
  await skipExplore(storage, '001-safe-state');
  const before = await storage.read('specs/001-safe-state/workflow-events.jsonl');

  const bootstrappedAgain = await engine.bootstrap('001-safe-state');
  assert.deepEqual(bootstrappedAgain.completedStages, ['explore']);
  assert.equal(await storage.read('specs/001-safe-state/workflow-events.jsonl'), before);

  const prepared = await engine.prepareStage('001-safe-state', 'grill');
  const template = await storage.read('specs/001-safe-state/decision-log.md');
  assert.match(template, /^# 决策日志/m);
  assert.match(template, /## 提示契约/);
  assert.match(template, /## 权威规则/);
  assert.match(prepared.prompt, /# 阶段：grill/);
  assert.doesNotMatch(template, /Generated by|Prompt Contract|Authority Rules/);
  await assert.rejects(
    engine.completeStage('001-safe-state', 'grill'),
    /still templates: decision-log\.md/,
  );
  await storage.write('specs/001-safe-state/decision-log.md', '# 决策\n\n已批准请求的行为。');
  const completed = await engine.completeStage('001-safe-state', 'grill');
  assert.deepEqual(completed.completedStages, ['explore', 'grill']);
});

test('implement tracks individual tasks and blocks stage completion while tasks remain', async () => {
  const { storage, engine } = createEngine();
  const events = new EventStore(storage);
  const path = 'specs/002-multi-task';
  await events.append(path, { type: 'BOOTSTRAP', featureId: '002-multi-task' });
  // Complete every stage up to (but not including) implement, then prepare it.
  const implementIndex = DEFAULT_WORKFLOW.stageOrder.indexOf('implement');
  for (const stage of DEFAULT_WORKFLOW.stageOrder.slice(0, implementIndex)) {
    await events.append(path, { type: 'STAGE_PREPARED', stage }, stage);
    await events.append(path, { type: 'STAGE_COMPLETE', stage, artifacts: [] }, stage);
  }
  await events.append(path, { type: 'STAGE_PREPARED', stage: 'implement' }, 'implement');
  await storage.write(`${path}/tasks.md`, '# Tasks\n\n- [ ] TASK-001: first\n- [ ] TASK-002: second\n');
  await storage.write(`${path}/change-manifest.md`, '# Changes\n\nTASK-001 implemented and verified.');

  let state = await engine.completeTask('002-multi-task', 'TASK-001');
  assert.deepEqual(state.completedTaskIds, ['TASK-001']);
  assert.equal(state.currentStage, 'implement');
  await assert.rejects(engine.completeStage('002-multi-task', 'implement'), /unfinished tasks: TASK-002/);

  await storage.write(`${path}/change-manifest.md`, '# Changes\n\nTASK-001 and TASK-002 implemented and verified.');
  state = await engine.completeTask('002-multi-task', 'TASK-002');
  assert.deepEqual(state.completedTaskIds, ['TASK-001', 'TASK-002']);
  state = await engine.completeStage('002-multi-task', 'implement');
  assert.equal(state.currentStage, 'converge');
});

test('event replay rejects a duplicate bootstrap event in a corrupted log', async () => {
  const storage = new MemoryStorage();
  const events = new EventStore(storage);
  const path = 'specs/003-corrupt';
  await events.append(path, { type: 'BOOTSTRAP', featureId: '003-corrupt' });
  await events.append(path, { type: 'BOOTSTRAP', featureId: '003-corrupt' });
  await assert.rejects(events.replay(path, DEFAULT_WORKFLOW), /Duplicate BOOTSTRAP/);
});

test('completeStage throws when stage was not prepared', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('004-no-prepare');
  await skipExplore(storage, '004-no-prepare');
  // grill stage exists, but prepareStage was never called
  await assert.rejects(
    engine.completeStage('004-no-prepare', 'grill'),
    /stage was not prepared/,
  );
});

test('prepareStage enables completeStage and records STAGE_PREPARED event', async () => {
  const { storage, engine } = createEngine();
  await engine.bootstrap('005-prepare-then-complete');
  await skipExplore(storage, '005-prepare-then-complete');
  const stateBefore = await engine.getState('005-prepare-then-complete');
  assert.deepEqual(stateBefore.preparedStages, []);

  await engine.prepareStage('005-prepare-then-complete', 'grill');
  const stateAfter = await engine.getState('005-prepare-then-complete');
  assert.deepEqual(stateAfter.preparedStages, ['grill']);

  await storage.write('specs/005-prepare-then-complete/decision-log.md', '# 决策\n\n已批准请求的行为。');
  const completed = await engine.completeStage('005-prepare-then-complete', 'grill');
  assert.deepEqual(completed.preparedStages, []);
  assert.deepEqual(completed.completedStages, ['explore', 'grill']);
});
